# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be45539b92a518f8228ef95d3728fde7c013ce280186d5dcdc084274282d1d05fe89162a0993e0014c1c734a99118fd6a6b4a74671cb3cd3f28643b9441a6541

test:
  secret_key_base: bc136b6cbb960c1d8689ba5d6dc84cbf9c852d5a0270a2b604e7042114d3ccaf7017af668c363e573e4c79a142df35583dc0b6c6a294b2f91c2bd2926273bb66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
